openapi: 3.0.0
info:
  title: founder-matching-api
  version: "1.0.0"
  description: The API for the FounderMatching project by HarDeconstruction

servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DUCLNC2004/FounderMatching/1.0.0

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    # ENUMS
    GenderType:
      type: string
      enum:
        - male
        - female
        - other

    PrivacyType:
      type: string
      enum:
        - public
        - private
        - connections

    MatchStatus:
      type: string
      enum:
        - pending
        - accepted
        - rejected

    # TABLE SCHEMAS
    UserAccount:
      type: object
      additionalProperties: false
      properties:
        UserID:
          type: integer
          format: int32
          minimum: 1
          maximum: 99999999
        ClerkUserID:
          type: string
          format: uuid
          maxLength: 200
          pattern: "^[A-Za-z0-9_-]+$"
        Email:
          type: string
          format: email
          maxLength: 255
          pattern: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
        FirstName:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z\\s'-]+$"
        LastName:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z\\s'-]+$"
        IsCandidate:
          type: boolean
        IsStartup:
          type: boolean
      required:
        - ClerkUserID
        - Email
        - FirstName
        - LastName

    CandidateProfile:
      type: object
      additionalProperties: false
      properties:
        CandidateID:
          type: integer
          format: int32
          minimum: 1
          maximum: 99999999
        UserID:
          type: integer
          format: int32
          minimum: 1
          maximum: 99999999
        Industry:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z\\s&,-]+$"
        PhoneNumberID:
          type: integer
          format: int32
          minimum: 1
          maximum: 999999999999
        CountryID:
          type: integer
          format: int32
          minimum: 1
          maximum: 99999999
        City:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z\\s'-]+$"
        University:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z0-9\\s',.-]+$"
        LinkedInURL:
          type: string
          format: url
          maxLength: 255
          pattern: "^https?://(www\\.)?linkedin\\.com/.*$"
        Slogan:
          type: string
          maxLength: 300
          pattern: "^[A-Za-z0-9]+$"
        HobbyInterest:
          type: string
          maxLength: 500
          pattern: "^[A-Za-z0-9]+$"
        Gender:
          $ref: '#/components/schemas/GenderType'
      required:
        - UserID
        - Industry
        - Gender

    CandidateProfilePrivacySettings:
      type: object
      additionalProperties: false
      properties:
        CandidateID:
          type: integer
          format: int32
          minimum: 1
          maximum: 99999999
        GenderPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        IndustryPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        PhoneNumberIDPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        CountryIDPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        CityPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        UniversityPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        LinkedInURLPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        SloganPrivacy:
          $ref: '#/components/schemas/PrivacyType'
        HobbyInterestPrivacy:
          $ref: '#/components/schemas/PrivacyType'
      required:
        - CandidateID

    StartupProfile:
      type: object
      additionalProperties: false
      properties:
        StartupID:
          type: integer
          format: int32
          minimum: 1
          maximum: 999999
        UserOwnerID:
          type: integer
          format: int32
          minimum: 1
        Name:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z0-9\\s&',.-]+$"
        Email:
          type: string
          format: email
          maxLength: 255
          pattern: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$"
        Logo:
          type: string
          format: url
          maxLength: 255
        Industry:
          type: string
          maxLength: 100
        PhoneNumberID:
          type: integer
          format: int32
          minimum: 1
        CountryID:
          type: integer
          format: int32
          minimum: 1
        City:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z\\s'-]+$"
        LinkedInURL:
          type: string
          format: url
          maxLength: 255
        Slogan:
          type: string
          maxLength: 200
        WebsiteLink:
          type: string
          format: url
          maxLength: 255
        Description:
          type: string
          maxLength: 2000
        CurrentStage:
          type: string
          maxLength: 2000
        Achievement:
          type: string
          maxLength: 2000
      required:
        - UserOwnerID
        - Name
        - Email
        - Industry

    Notification:
      type: object
      additionalProperties: false
      properties:
        ID:
          type: integer
          format: int32
        Recipient:
          type: integer
          format: int32
        Data:
          type: string
          maxLength: 2000
          pattern: "^[A-Za-z0-9]+$"
        Read:
          type: boolean
          default: false
        CreatedDateTime:
          type: string
          format: date-time
          maxLength: 25
          pattern: "^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])T([01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(\\.\\d+)?(Z|[+-][01]\\d:[0-5]\\d)?$"
        IsStartupNotified:
          type: boolean
          default: false
      required:
        - Recipient
        - Read
        - CreatedDateTime

    Tags:
      type: object
      additionalProperties: false
      properties:
        ID:
          type: integer
          format: int32
        Value:
          type: string
          maxLength: 50
        Description:
          type: string
          maxLength: 2000
      required:
        - Value

    Experience:
      type: object
      additionalProperties: false
      properties:
        ID:
          type: integer
          format: int32
        CandidateOwner:
          type: integer
          format: int32
        CompanyName:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z0-9\\s&',.-]+$"
        Role:
          type: string
          maxLength: 100
        Location:
          type: string
          maxLength: 100
          pattern: "^[A-Za-z\\s'-]+$"
        Description:
          type: string
          maxLength: 2000
        StartDate:
          type: string
          format: date
        EndDate:
          type: string
          format: date
      required:
        - CandidateOwner
        - CompanyName

paths:
  /users/me:
    get:
      tags:
        - Profile
      summary: Get the current user's profile
      description: Fetch the profile details of the logged-in user, including basic and candidate-specific information.
      operationId: getUserProfile
      responses:
        '200':
          description: User profile details.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  UserAccount:
                    $ref: '#/components/schemas/UserAccount'
                  CandidateProfile:
                    $ref: '#/components/schemas/CandidateProfile'
                  PrivacySettings:
                    $ref: '#/components/schemas/CandidateProfilePrivacySettings'
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Profile not found."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"

    post:
      tags:
        - Profile
      summary: Create a new user profile
      description: Create a profile for the logged-in user.
      operationId: createUserProfile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                UserAccount:
                  $ref: '#/components/schemas/UserAccount'
                CandidateProfile:
                  $ref: '#/components/schemas/CandidateProfile'
                PrivacySettings:
                  $ref: '#/components/schemas/CandidateProfilePrivacySettings'
      responses:
        '200':
          description: Profile created successfully.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Profile created successfully."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '404':
          description: Profile creation failed.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Profile creation failed."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"

    patch:
      tags:
        - Profile
      summary: Update the current user's profile
      description: Update profile information for the logged-in user.
      operationId: updateUserProfile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                UserAccount:
                  $ref: '#/components/schemas/UserAccount'
                CandidateProfile:
                  $ref: '#/components/schemas/CandidateProfile'
                PrivacySettings:
                  $ref: '#/components/schemas/CandidateProfilePrivacySettings'
      responses:
        '200':
          description: Profile updated successfully.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Profile updated successfully."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '404':
          description: Profile not found
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Profile not found."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"

  /notifications:
    get:
      tags:
        - Notifications
      summary: Get all notifications for the current user
      description: Fetch all notifications for the logged-in user.
      operationId: getNotifications
      responses:
        '200':
          description: Notifications fetched successfully.
          content:
            application/json:
              schema:
                type: array
                maxItems: 50
                items:
                  $ref: '#/components/schemas/Notification'
        '404':
          description: Notifications not found
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Notification not found."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"

  /notifications/{id}:
    patch:
      tags:
        - Notifications
      summary: Mark a notification as read
      description: Update the read status of a specific notification by ID.
      operationId: markNotificationAsRead
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 2147483647
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties: false
              properties:
                Read:
                  type: boolean
                  example: true
      responses:
        '200':
          description: Notification updated successfully.
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Notification updated successfully."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  message:
                    type: string
                    example: "Notification not found."
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "Unauthorized access"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  error:
                    type: string
                    example: "An unexpected error occurred"
                    maxLength: 100
                    pattern: "^[A-Za-z0-9 ,.?!'-]+$"
